FROM node:20-alpine

#  Working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the application code
COPY . .


CMD ["npm", "run", "start:dev"]