
FROM node:20.19.4-alpine3.21 AS base

# Build stage
FROM base AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npx prisma generate


RUN npm run build

# Production stage
FROM base 

WORKDIR /app

COPY --from=builder /app/dist ./dist


CMD ["npm", "run", "start:prod"]
